pipeline {
  agent any

  tools {
      nodejs 'nodejs'
  }

  environment {
      // General Variables for Pipeline      
      PROJECT_ROOT = 'express-mysql/app'
      EMAIL_ADDRESS = 'jesus.brayan.payegmail.com'
      REGISTRY = 'mykrampus/docker-pirate-express'
  }

  stages {
      stage('Hello') {
        steps {
          // init 
          echo 'Starting  project automation'
        }
      }
      stage('Checkout') {
        steps {
        // Get Github repo using Github 
        checkout([$class: 'GitSCM', branches: [[name: '*/v2.1-main-work']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jesusBray/docker-pirate']]])        }
      }
      stage('Install dependencies') {
        steps {
          sh 'npm --version'
          sh "cd ${PROJECT_ROOT}; npm install"
        }
      }
      stage('Unit tests') {
        steps {
          // Run unit tests
          sh "cd ${PROJECT_ROOT}; npm run test"
        }
      }
      stage('Generate coverage report') {
        steps {
          // Run code-coverage reports
          sh "cd ${PROJECT_ROOT}; npm run coverage"
        }
      }
      stage('Build docker-image') {
        steps {
          sh "cd ./${PROJECT_ROOT};docker build -t ${REGISTRY}:${BUILD_NUMBER} . "
        }
      }
      stage('Deploy docker-image') {
        steps {
          // Dockerhub
          sh 'docker login'
          sh "docker push ${REGISTRY}:${BUILD_NUMBER}"
        }
      }
  }
}
